services:
  - type: web
    name: zep-http-server
    env: node
    plan: free
    rootDir: .
    buildCommand: pnpm install && pnpm build --filter http
    startCommand: pnpm --filter http start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_esV8DjmLFC2c@ep-noisy-violet-an2ljx30-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PORT
        value: 4000

  - type: web
    name: zep-ws-server
    env: node
    plan: free
    rootDir: .
    buildCommand: pnpm install && pnpm build --filter ws
    startCommand: pnpm --filter ws start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_esV8DjmLFC2c@ep-noisy-violet-an2ljx30-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PORT
        value: 8080
